fix(rum-vue): vue 3 support
elastic/apm-agent-rum-js pull request #1092
Opened 2021-10-15 14:07 UTC by mdschweda

This change introduces Vue 3 support / fixes an error when loading the plugin in Vue 3.

See also https://v3.vuejs.org/guide/migration/global-api.html#vue-prototype-replaced-by-config-globalproperties

Tested on an ECK staging environment with a real world app.

Closes #1058

2021-10-21 04:36 UTC, mdschweda commented
Without means to investigate the npm log I consider the CI pipeline error to be out of scope of this PR. Apparently, error 137 indicates insufficient RAM on the test node. I will remove the semicolon that causes a prettier warning in a last commit --amend if there are no further requests from your side

2021-11-11 14:52 UTC, alfkonee commented
@vigneshshanmugam  Please any Progress on this

2021-11-16 18:03 UTC, mdschweda commented
@alfkonee There are still problems with the e2e tests. I can't access the logs. They run on saucelabs and I don't feel like paying 200 bucks to finish the PR or make changes blindly and ask Vignesh to manually hit the pipeline button for me on the off chance to fix the problem by accident. I'll try to get the tests to run locally when I find some time even though that was a nightmare last time I tried.

2021-11-17 22:15 UTC, alfkonee requested changes
@mdschweda  I'd suggest you use `JSON.stringify()` on the reason object for the affected to help make the reason clearer to read in the logs at the foloowing positions
in 
\packages\rum-core\test\performance-monitoring\performance-monitoring.spec.js:612
```suggestion 
-            `Failed sending http-request transaction to the server, reason: ${reason}`
+           `Failed sending http-request transaction to the server, reason: ${JSON.stringify(reason)}`
```
\packages\rum-core\test\performance-monitoring\performance-monitoring.spec.js:190
```suggestion 
-'Failed sending page load metrics so the server, reason: ' +
-                reason
+'Failed sending page load metrics so the server, reason: ' +
+                JSON.stringify(reason)
```

2021-12-03 20:27 UTC, vigneshshanmugam reviewed
Thanks @mdschweda for the PR, Looks good to me. 

I will push some changes
- NPM 6 stuff
- Package version change

Should be good to go after that. Apologies for the delay in getting this in.

2021-12-03 20:27 UTC, vigneshshanmugam commented on packages/rum-vue/package.json
> +  "version": "1.3.2",
will publish it as 2.0.0 as its breaking change and also to keep 1.x focussed on prior vue versions.

2021-12-03 20:31 UTC, vigneshshanmugam commented on packages/rum-vue/package.json
> +  "version": "1.3.2",
Switched to 1.3.1 as before, will be changed by our release script when doing major bump.

2021-12-04 07:04 UTC, vigneshshanmugam commented
Vue 3 dropped support for IE 11 and webpack build is timing out. Have to change the browser list for vue package and change to dev mode to fix the build. Will take care of it from my side.

2021-12-09 01:01 UTC, vigneshshanmugam commented
/test

2021-12-09 17:52 UTC, vigneshshanmugam commented
Waiting for the CI issue to get fixed - #1111

2021-12-13 18:58 UTC, vigneshshanmugam approved these changes
LGTM. Thanks @mdschweda, Here are the next steps

- I will update the docs to reflect 1.x support for vue 2 and 2.x for vue 3
- Will do a release for 2.0.0 for `@elastic/apm-rum-vue`

2021-12-13 18:58 UTC, merged