feat(rum-react): add render/children prop support
elastic/apm-agent-rum-js pull request #913
Opened 2020-10-07 13:15 UTC by vigneshshanmugam

+ fix #905

2020-10-07 14:35 UTC, apmmachine commented
### :package: Bundlesize report

Filename | Size(bundled) | Size(gzip) | Diff(gzip)
 --- | --- | --- | ---
elastic-apm-opentracing.umd.min.js | 61.7 KiB | 19.6 KiB |  :green_heart: 0 Bytes 
elastic-apm-rum.umd.min.js | 55.7 KiB | 18.2 KiB |  :green_heart: 0 Bytes 

<!--COMMENT_GENERATED_WITH_ID_bundlesize-->

2020-10-07 14:35 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-913/detail/PR-913/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-913/detail/PR-913/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-913/detail/PR-913/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-913/detail/PR-913/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #913 opened]`

* Reason: `Aborted from #2`

* Start Time: 2020-10-07T13:16:04.111+0000

* Duration: 79 min 13 sec


* Commit: d783cabdca0e7e6c96b7817432f20aa57813a1cf



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 1028  |
| Skipped      | 10 |
| Total        | 1038   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-913/detail/PR-913/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Error signal`
    * Description: The test failed
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-07T13:55:19.421+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/pipelines/PR-913/runs/1/steps/1827/log)
    
  
  * **Name**: `Start Elastic Stack 8.0.0-SNAPSHOT - @elastic/apm-rum-vue - saucelabs`
    * Description: 
    
    * Duration: 5 min 15 sec
    
    * Start Time: 2020-10-07T14:16:48.122+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/pipelines/PR-913/runs/1/steps/2149/log)
    
  
  * **Name**: `Error signal`
    * Description: 
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-07T14:22:03.307+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/pipelines/PR-913/runs/1/steps/2152/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-07T14:35:05.020Z] [Cobertura] Skipping Cobertura coverage report as build was not FAILURE or better ...
[2020-10-07T14:35:05.020Z] 
[2020-10-07T14:35:05.082Z] Publishing Coverage report....
[2020-10-07T14:35:05.699Z] A total of 5 reports were found
[2020-10-07T14:35:05.700Z] Source File Navigation is enabled - Current level: STORE_ALL_BUILD
[2020-10-07T14:35:05.701Z] 41 source files need to be copied.
[2020-10-07T14:35:07.486Z] Starting copy source file src/common/throttle.js. 
[2020-10-07T14:35:07.862Z] Unable to find source file src/common/throttle.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:07.862Z] Starting copy source file src/opentracing/tracer.js. 
[2020-10-07T14:35:08.045Z] Unable to find source file src/opentracing/tracer.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:08.045Z] Starting copy source file src/common/truncate.js. 
[2020-10-07T14:35:08.240Z] Unable to find source file src/common/truncate.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:08.241Z] Starting copy source file src/common/patching/history-patch.js. 
[2020-10-07T14:35:08.430Z] Unable to find source file src/common/patching/history-patch.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:08.430Z] Starting copy source file src/common/patching/patch-utils.js. 
[2020-10-07T14:35:08.612Z] Unable to find source file src/common/patching/patch-utils.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:08.612Z] Starting copy source file src/common/config-service.js. 
[2020-10-07T14:35:08.805Z] Unable to find source file src/common/config-service.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:08.805Z] Starting copy source file src/common/patching/event-target-patch.js. 
[2020-10-07T14:35:09.001Z] Unable to find source file src/common/patching/event-target-patch.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:09.001Z] Starting copy source file src/error-logging/stack-trace.js. 
[2020-10-07T14:35:09.177Z] Unable to find source file src/error-logging/stack-trace.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:09.177Z] Starting copy source file src/error-logging/index.js. 
[2020-10-07T14:35:09.536Z] Unable to find source file src/error-logging/index.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:09.536Z] Starting copy source file src/performance-monitoring/index.js. 
[2020-10-07T14:35:09.717Z] Unable to find source file src/performance-monitoring/index.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:09.718Z] Starting copy source file src/performance-monitoring/transaction-service.js. 
[2020-10-07T14:35:09.868Z] Unable to find source file src/performance-monitoring/transaction-service.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:09.868Z] Starting copy source file src/performance-monitoring/span-base.js. 
[2020-10-07T14:35:10.022Z] Unable to find source file src/performance-monitoring/span-base.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.023Z] Starting copy source file src/common/instrument.js. 
[2020-10-07T14:35:10.181Z] Unable to find source file src/common/instrument.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.181Z] Starting copy source file src/common/context.js. 
[2020-10-07T14:35:10.359Z] Unable to find source file src/common/context.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.359Z] Starting copy source file src/common/apm-server.js. 
[2020-10-07T14:35:10.520Z] Unable to find source file src/common/apm-server.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.520Z] Starting copy source file src/performance-monitoring/capture-navigation.js. 
[2020-10-07T14:35:10.673Z] Unable to find source file src/performance-monitoring/capture-navigation.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.673Z] Starting copy source file src/common/patching/index.js. 
[2020-10-07T14:35:10.837Z] Unable to find source file src/common/patching/index.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:10.837Z] Starting copy source file src/performance-monitoring/span.js. 
[2020-10-07T14:35:11.010Z] Unable to find source file src/performance-monitoring/span.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agent-rum-mbp_PR-913
[2020-10-07T14:35:11.010Z] Starting copy source file src/opentracing/span.js. 
[2020-10-07T14:35:11.197Z] Unable to find source file src/opentracing/span.js in workspace /var/lib/jenkins/workspace/ent-rum_apm-agen [...]

2020-10-08 09:22 UTC, jahtalab requested changes
Thanks @vigneshshanmugam 

[There are some logical differences](https://reactrouter.com/web/api/Route) between using `children`, `component` and `render` props with the `Route` component. At the moment we're always passing a component (regardless of the original prop). I think we should investigate if we can minimise the effect of these differences, or document them if we can't.

2020-10-08 09:31 UTC, vigneshshanmugam commented on packages/rum-react/src/get-with-transaction.js
> +        loggingService.warn(`${name} is not instrumented by the agent`)
Yes only if its null.

2020-10-08 09:33 UTC, vigneshshanmugam commented
@jahtalab I went though the source code of the Route before proposing the change, There is no such such key difference that would kill the performance of the app under different circumstance, they are all the same under the hood (functions), For React it does not matter. 

Happy to add documentation. Let me know your thoughts.

2020-10-12 11:42 UTC, jahtalab commented
@vigneshshanmugam , The differences are mentioned in their docs (linked above), more specifically:

> When you use component (instead of render or children, below) the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function to the component prop, you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the render or the children prop (below)

This ^ seems to affect the performance, but more importantly it affects the functionality of the application, i.e. unmounting/mounting the component.

Also this part:

> Sometimes you need to render whether the path matches the location or not. In these cases, you can use the function children prop. It works exactly like render except that it gets called whether there is a match or not. The children render prop receives all the same route props as the component and render methods, except when a route fails to match the URL, then match is null. This allows you to dynamically adjust your UI based on whether or not the route matches

This also seems a difference in functionality depending on which prop is passed.

2020-10-30 09:22 UTC, jahtalab commented
Meeting:
- We should add a test to verify the difference explain in the react-router docs
- We should add test from #924
- We should add to documents how it works in and what user might need to be aware of.

2021-08-08 13:44 UTC, ikalkov commented
Any updates here?

2023-08-07 18:16 UTC, closed without merging