Add eventtarget to the Instrumentation Types
elastic/apm-agent-rum-js pull request #920
Opened 2020-10-13 23:35 UTC by ksivamuthu

Add eventtarget to the instrumentation types.

2020-10-13 23:38 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-920/detail/PR-920/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-920/detail/PR-920/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-920/detail/PR-920/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-920/detail/PR-920/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #920 opened]`

* Reason: `The PR is not allowed to run in the CI yet`

* Start Time: 2020-10-13T23:35:10.958+0000

* Duration: 3 min 7 sec


* Commit: 9e6da6753d459e4c1e4f50cf11d9c05523070ca4




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-rum%2Fapm-agent-rum-mbp%2FPR-920/detail/PR-920/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Error signal`
    * Description: githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permission
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-10-13T23:38:09.995+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-rum/pipelines/apm-agent-rum-mbp/pipelines/PR-920/runs/1/steps/79/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-10-13T23:38:02.992Z] Checking out Revision 9e6da6753d459e4c1e4f50cf11d9c05523070ca4 (PR-920)
[2020-10-13T23:38:03.042Z] Commit message: "Add eventtarget to the Instrumentation Types"
[2020-10-13T23:38:03.042Z] Cleaning workspace
[2020-10-13T23:38:03.100Z]  > git --version # timeout=10
[2020-10-13T23:38:03.104Z]  > git --version # 'git version 2.17.1'
[2020-10-13T23:38:03.111Z] fatal: bad object 48afa17b18ceb9e9233383a774e9717394d6a1b7
[2020-10-13T23:38:02.904Z]  > git config core.sparsecheckout # timeout=10
[2020-10-13T23:38:02.912Z]  > git checkout -f 9e6da6753d459e4c1e4f50cf11d9c05523070ca4 # timeout=15
[2020-10-13T23:38:02.958Z]  > git remote # timeout=10
[2020-10-13T23:38:02.962Z]  > git config --get remote.origin.url # timeout=10
[2020-10-13T23:38:02.972Z] using GIT_SSH to set credentials GitHub user @elasticmachine SSH key
[2020-10-13T23:38:02.977Z]  > git merge 4de1490c6a08260423d42176d999819408d158e5 # timeout=10
[2020-10-13T23:38:02.989Z]  > git rev-parse HEAD^{commit} # timeout=10
[2020-10-13T23:38:02.999Z]  > git config core.sparsecheckout # timeout=10
[2020-10-13T23:38:03.002Z]  > git checkout -f 9e6da6753d459e4c1e4f50cf11d9c05523070ca4 # timeout=15
[2020-10-13T23:38:03.048Z]  > git rev-parse --verify HEAD # timeout=10
[2020-10-13T23:38:03.056Z] Resetting working tree
[2020-10-13T23:38:03.056Z]  > git reset --hard # timeout=10
[2020-10-13T23:38:03.065Z]  > git clean -fdx # timeout=10
[2020-10-13T23:38:04.277Z] Masking supported pattern matches of $GIT_USERNAME or $GIT_PASSWORD
[2020-10-13T23:38:04.934Z] + git fetch https://****:****@github.com/elastic/apm-agent-rum-js.git +refs/pull/*/head:refs/remotes/origin/pr/*
[2020-10-13T23:38:06.401Z] Archiving artifacts
[2020-10-13T23:38:07.229Z] + git rev-parse HEAD
[2020-10-13T23:38:07.643Z] + git rev-parse HEAD
[2020-10-13T23:38:07.980Z] + git rev-parse origin/pr/920
[2020-10-13T23:38:08.052Z] [INFO] githubEnv: Found Git Build Cause: pr
[2020-10-13T23:38:08.441Z] Masking supported pattern matches of $GITHUB_TOKEN
[2020-10-13T23:38:09.470Z] [WARN] githubApiCall: The REST API call https://api.github.com/repos/elastic/apm-agent-rum-js/pulls/920/reviews return 0 elements
[2020-10-13T23:38:09.565Z] [INFO] githubPrCheckApproved: Title: Add eventtarget to the Instrumentation Types - User: ksivamuthu - Author Association: FIRST_TIME_CONTRIBUTOR
[2020-10-13T23:38:10.022Z] ERROR: githubPrCheckApproved: The PR is not allowed to run in the CI yet
[2020-10-13T23:38:10.022Z] ERROR: githubPrCheckApproved: The PR is not allowed to run in the CI yet. (Only users with write permissions can do so.)
[2020-10-13T23:38:10.138Z] [INFO] Let's stop build #1. The PR is not allowed to run in the CI yet
[2020-10-13T23:38:10.173Z] Sleeping for 5 sec
[2020-10-13T23:38:11.425Z] Stage "Lint" skipped due to earlier failure(s)
[2020-10-13T23:38:11.554Z] Stage "Test Pupperteer" skipped due to earlier failure(s)
[2020-10-13T23:38:12.286Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.296Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.305Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.313Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.322Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.331Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.339Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum-react'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.348Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum-react'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.357Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum-react'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.366Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum-angular'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.375Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum-angular'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.385Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum-angular'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.394Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum-vue'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.404Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum-vue'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.416Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum-vue'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.791Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.806Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.816Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.825Z] Stage "Matrix - STACK_VERSION = '8.0.0-SNAPSHOT', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.834Z] Stage "Matrix - STACK_VERSION = '7.7.0', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.843Z] Stage "Matrix - STACK_VERSION = '7.0.0', SCOPE = '@elastic/apm-rum-core'" skipped due to earlier failure(s)
[2020-10-13T23:38:12.853Z] Stage "Matrix - STACK_VERSI [...]

2020-10-30 11:17 UTC, vigneshshanmugam approved these changes
Thanks @ksivamuthu

2020-11-16 14:59 UTC, jahtalab requested changes
Thanks @ksivamuthu ! 
would you please sign the CLA?
Also the lint task is failing, I've added a suggestion to fix that.

2020-11-16 14:59 UTC, jahtalab commented on packages/rum/src/index.d.ts
> +
```suggestion
```

2021-02-08 18:59 UTC, vigneshshanmugam approved these changes
Will fix the commit message issue while merging.

2021-02-08 19:00 UTC, merged